name: Deploy

on:
  push:
    branches: [ staging ]

jobs:
 build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Configure SSH Key and pull latest code
      env:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "$PRIVATE_KEY" > private_key
        chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.USER_NAME }}@${{ secrets.SSH_HOST }} '
        cd /home/ec2-user/Vijay-Johar-Coaching &&
        git branch &&
        git pull &&
        npm i &&
        npm i stylis-plugin-rtl@2.0.2
        npm start '
