name: Deploy

on:
  push:
    branches: [ staging ]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v2 
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{secrets.SSH_HOST}}
            USER_NAME: ${{secrets.USER_NAME}}
      
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} 

              # Now we have got the access of EC2 and we will start the deploy .
               ls
               git clone https://github.com/amansharmareact/Vijay-Johar-Coaching.git &&
              cd /home/ec2-user/Vijay-Johar-Coaching
              #git checkout dev
